adjust unicorne vial keymap
- home row mods
- bilateral combinations
- only build boardsource unicorne

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,5 +1,5 @@
 name: CI
-on: [ pull_request, push, workflow_dispatch ]
+on: [pull_request, push, workflow_dispatch]
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -17,13 +17,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: (actions) Checkout Vial repo
-      uses: actions/checkout@v4
-      with:
-        persist-credentials: false
+      - name: (actions) Checkout Vial repo
+        uses: actions/checkout@v4
+        with:
+          persist-credentials: false
 
-    - name: Verify Vial UID is unique per-keyboard
-      run: python3 util/ci_vial_verify_uid.py
+      - name: Verify Vial UID is unique per-keyboard
+        run: python3 util/ci_vial_verify_uid.py
 
   build-default:
     name: Build default keymaps for Vial
@@ -33,35 +33,35 @@ jobs:
       KEYMAP: default
 
     steps:
-    - name: (actions) Checkout Vial repo
-      uses: actions/checkout@v4
-      with:
-        persist-credentials: false
-        submodules: recursive
+      - name: (actions) Checkout Vial repo
+        uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+          submodules: recursive
 
-    - name: Build
-      id: build
-      run: |
-        git config --global --add safe.directory $(pwd)
-        if ! qmk mass-compile -j $(nproc) $(qmk find -km vial | sed "s/:vial$/:${KEYMAP}/");
-          then
-          echo "::error::$(ls -1 .build/failed.log.* | wc -l) keymaps failed to build. See logs and/or job summary for details."
-          exit 1
-        fi
+      - name: Build
+        id: build
+        run: |
+          git config --global --add safe.directory $(pwd)
+          if ! qmk compile -j $(nproc) -kb boardsource/unicorne -km ${KEYMAP};
+            then
+            echo "::error::$(ls -1 .build/failed.log.* | wc -l) keymaps failed to build. See logs and/or job summary for details."
+            exit 1
+          fi
 
-    - name: Dump failure logs
-      if: ${{ failure() && steps.build.conclusion == 'failure' }}
-      run: |
-        echo '### Failure logs' | tee -a "${GITHUB_STEP_SUMMARY}"
+      - name: Dump failure logs
+        if: ${{ failure() && steps.build.conclusion == 'failure' }}
+        run: |
+          echo '### Failure logs' | tee -a "${GITHUB_STEP_SUMMARY}"
 
-        cd .build || exit 1
-        for log in failed.log.*; do
-          pretty_logname="$(echo "${log}" | sed "s/^failed\.log\.[0-9]\+\.// ; s/\.${KEYMAP}$//")"
+          cd .build || exit 1
+          for log in failed.log.*; do
+            pretty_logname="$(echo "${log}" | sed "s/^failed\.log\.[0-9]\+\.// ; s/\.${KEYMAP}$//")"
 
-          printf '\n::group::%s\n%s\n::endgroup::\n' "${pretty_logname}" "$(sed "${REGEX_MAKE_OUTPUT}" < "${log}")"
-          printf '\n<details>\n<summary>%s</summary>\n\n```\n%s\n```\n\n</details>\n' \
-             "${pretty_logname}" "$(sed "${REGEX_MAKE_OUTPUT} ; ${REGEX_ANSI_COLOR}" < "${log}")" >> "${GITHUB_STEP_SUMMARY}"
-        done
+            printf '\n::group::%s\n%s\n::endgroup::\n' "${pretty_logname}" "$(sed "${REGEX_MAKE_OUTPUT}" < "${log}")"
+            printf '\n<details>\n<summary>%s</summary>\n\n```\n%s\n```\n\n</details>\n' \
+               "${pretty_logname}" "$(sed "${REGEX_MAKE_OUTPUT} ; ${REGEX_ANSI_COLOR}" < "${log}")" >> "${GITHUB_STEP_SUMMARY}"
+          done
 
   build-vial:
     name: Build Vial keymaps
@@ -71,32 +71,32 @@ jobs:
       KEYMAP: vial
 
     steps:
-    - name: (actions) Checkout Vial repo
-      uses: actions/checkout@v4
-      with:
-        persist-credentials: false
-        submodules: recursive
+      - name: (actions) Checkout Vial repo
+        uses: actions/checkout@v4
+        with:
+          persist-credentials: false
+          submodules: recursive
 
-    - name: Build
-      id: build
-      run: |
-        git config --global --add safe.directory $(pwd)
-        if ! qmk mass-compile -km "${KEYMAP}" -j $(nproc);
-          then
-          echo "::error::$(ls -1 .build/failed.log.* | wc -l) keymaps failed to build. See logs and/or job summary for details."
-          exit 1
-        fi
+      - name: Build
+        id: build
+        run: |
+          git config --global --add safe.directory $(pwd)
+          if ! qmk compile -j $(nproc) -kb boardsource/unicorne -km ${KEYMAP};
+            then
+            echo "::error::$(ls -1 .build/failed.log.* | wc -l) keymaps failed to build. See logs and/or job summary for details."
+            exit 1
+          fi
 
-    - name: Dump failure logs
-      if: ${{ failure() && steps.build.conclusion == 'failure' }}
-      run: |
-        echo '### Failure logs' | tee -a "${GITHUB_STEP_SUMMARY}"
+      - name: Dump failure logs
+        if: ${{ failure() && steps.build.conclusion == 'failure' }}
+        run: |
+          echo '### Failure logs' | tee -a "${GITHUB_STEP_SUMMARY}"
 
-        cd .build || exit 1
-        for log in failed.log.*; do
-          pretty_logname="$(echo "${log}" | sed "s/^failed\.log\.[0-9]\+\.// ; s/\.${KEYMAP}$//")"
+          cd .build || exit 1
+          for log in failed.log.*; do
+            pretty_logname="$(echo "${log}" | sed "s/^failed\.log\.[0-9]\+\.// ; s/\.${KEYMAP}$//")"
 
-          printf '\n::group::%s\n%s\n::endgroup::\n' "${pretty_logname}" "$(sed "${REGEX_MAKE_OUTPUT}" < "${log}")"
-          printf '\n<details>\n<summary>%s</summary>\n\n```\n%s\n```\n\n</details>\n' \
-            "${pretty_logname}" "$(sed "${REGEX_MAKE_OUTPUT} ; ${REGEX_ANSI_COLOR}" < "${log}")" >> "${GITHUB_STEP_SUMMARY}"
-        done
+            printf '\n::group::%s\n%s\n::endgroup::\n' "${pretty_logname}" "$(sed "${REGEX_MAKE_OUTPUT}" < "${log}")"
+            printf '\n<details>\n<summary>%s</summary>\n\n```\n%s\n```\n\n</details>\n' \
+              "${pretty_logname}" "$(sed "${REGEX_MAKE_OUTPUT} ; ${REGEX_ANSI_COLOR}" < "${log}")" >> "${GITHUB_STEP_SUMMARY}"
+          done
